### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by hmhei** [larikkai/PHoF#1]
Mielenkiintoinen ja tähän asti hyvin toteutettu tietokantasovellus. Projektin ulkoasu mukailee lähdemateriaalin esimerkkiä ja ohjeistuksia, ja on selkeä.

Työssä on yhteensä viisi tietokantataulua, ja kolme monesta-moneen yhteyttä liitostauluineen. Tämä on projektiohjeistuksen suositusten piirissä. Tietokantakaavio on erittäin selkeä vaikkakin hieman erilainen kuin Tikape-kurssilla ohjeistettu, mutta tämä lienee makuasia.

# Heroku

Työ toimii Herokussa ilman ongelmia, ja myös hyödyntää Herokun tarjoamaa PostgreSQL-tietokannanhallintajärjestelmää. 

Sisäänkirjautuminen, rekisteröityminen ja uloskirjautuminen käyttäjänä on toteutettu, kuten myös pelien ja turnausten lisääminen tiettyine ominaisuuksineen ("player count" ja "status"). Turnauksen kohdalla statusta "Finished" voi vaihtaa kumpaankin suuntaan (false -> true -> false), pelien kohdalla statuksen vaihto näyttää toimivan tällä hetkellä vain suuntaan false -> true. Ei käynyt aivan selväksi, onko tämä ero tarkoituksella tehty?

Sovellus näyttää pitävän myös kirjaa kunkin käyttäjän pelaamien pelien määrästä. Mikäli ymmärsin oikein, tämä ominaisuus osoittaa (ainakin tällä hetkellä) kunkin pelin sille käyttäjälle, joka asettaa kyseisen pelin statukseksi "true". Mikäli kyseisen pelin poistaa, poistuu tämä pelatun pelin tieto myös käyttäjän pelimäärästä. Sovelluksessa pääsee muiden valikoiden lisäksi myös näppärästi takaisin etusivulle.

# Dokumentaatio

Dokumentaatio (readme, tietokantakaavio ja käyttötapaukset) on toteutettu erittäin huolellisesti ja laajasti. Käyttötapauksia on listattu runsaasti, ja ne on niputettu hyvin aliotsikoiden alle.

Admin-toiminnallisuus on listattu käyttötapauksiin, mutta sitä ei ilmeisesti ole vielä toteutettu itse sovellukseen, eli se tullee myöhemmin testattavaksi.

Käyttötapaukset on tällä hetkellä toteutettu .pdf -muodossa. Mikäli tämä puoli työstä on jo valmis, en näe siinä ongelmaa. Muussa tapauksessa harkitsisin Markdown -tyyppistä toteutusta, sillä se lienee näppärämpi modifioida ja tavallaan myös mukavampi lukea Githubissa.

# Koodi

Projektin rakenne ja koodi noudattelee lähdemateriaalin antamaa hyvää esimerkkiä. Koodi on kauttaaltaan varsin selkeää, ja funktioiden sekä muuttujien nimet ovat kuvaavia ja johdonmukaisia. Toisteista tietoa on siirretty ohjeistetun mukaisesti abstraktiin Base-luokkaan. Työssä on myös jo implementoitu muutama monimutkaisempi yhteenvetokysely.

Validointi on myös toteutettu, ja minimimerkkimäärät asetettu. Samalla voisi myös harkita maksimimerkkimäärän asettamista, ainakin tiettyihin kenttiin.

Sovelluksen HTML-koodissa on otettu käyttöön Bootstrap-kirjasto ulkoasun määrittelyä varten, ja sen toteutus on toimiva.

Kaiken kaikkiaan hyvää työtä tähän mennessä!

**Comment by larikkai** [comment]
Hei,

- Tapahtuman statuksen suora asettaminen ja muuttaminen tulee poistumaan. Status tulee muuttumaan automaattisesti kun tulos lisätään.

- PDF formaatti kankea käyttötapauksiin ja vaihdettu toteutus Markdown muotoon.

Kiitos palautteesta.
