### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by RoniNiklas** [larikkai/PHoF#2]
Hei,

tässä jotain korjausehdotuksia herokun version pohjalta. 24.2. klo 18.

# Käyttöliittymä
½. Sivusto antoi 500 server errorin ekalla käynnistyksellä, joskin toimi sitten tokalla. En tiedä onko toistuva virhe.
1. Signupissa pyydetään lukemaan säännöt, joita ei kumminkaan siinä näkymässä ole missään.  Esim. linkki siihen rules sanan kohtaan olisi asianmukainen tapa linkata näihin käyttösääntöihin.   
http://padel-hall-of-fame.herokuapp.com/auth/signup  
2. "Reading news is mandatory for all users" on outo lause. Mandatory tarkoittaa välttämätöntä, ja on outoa että uutisten lukeminen on välttämätöntä.   
http://padel-hall-of-fame.herokuapp.com/   
3. News sivuston toiminta outoa. Ensinnäkin siinä on admin login nappula, kun admin logini voisi olla muiden loginien kanssa samassa paikassa. Toisekseen, "write new news" vaatii uutta kirjautumista, ja kirjautumisnappulan painaminen johtaa takaisin etusivulle, ja itse kirjoittamisnäkymään ei pääse millään. Mahdollisesti news/views.py vaatii admin loginin uuden uutisen formin näkemiseen, mutta voisit piilottaa nuo napit kanssa, jos peruskäyttäjä ei niillä tee mitään. Eri valinnat voisi myös olla tasaisesti näytön keskellä, eikä vähän oudosti oikealle offsettinä.  
http://padel-hall-of-fame.herokuapp.com/news/  
3. Add a game ja list games toimii about odotetusti, joskin vähän vaihtelee onko sama peli 2v2 tai 1v1 eri näkymissä. Pelaajan/tiimin pisteet voi mennä yli ja ali ilmoitetun pistemäärän.
4. Add a tournament formi jostain syystä ihan sivun alareunassa. Toimii muuten kumminkin kuten pitääkin.   
5. Courts nappi menupalkissa vie tournaments näkymään.   Ei kannata lisätä menupalkkiin asioita, jotka ei ole vielä käytössä, vaan devata yksi alue kerrallaan loppuun, ennenkuin siirtyy lisäämään seuraavan osia minnekään.
6. Menupalkki liikkuu vähän sivulle eri näkymissä. Voisi pysyä paikallaan :D. 
7. Githubissa näkyvät admin tunnukset eivät tunnu toimivan. Test_user tunnukset toimivat ja oman käyttäjän voi kumminkin luoda ihan hyvin.
8. Englanti vaatii vielä vähän työstöä :D. Etenkin etusivun "see you in courts" voisi vaihtaa "see you on the courts". "See you in court" tarkoittaa, että nähdään oikeussalissa, kun taas "on the courts" tarkoittaisi kentillä.

# Itse koodi
1. Aika monessa kansiossa tyhjä init.py file 
2. Post-request käyttäjän poistamiselle ei vaadi admin oikeuksia. Teknisesti kuka tahansa voisi laittaa nyt poistopyyntöjä, kunhan tietää toisen käyttäjän käyttäjäid:n. 
https://github.com/larikkai/PHoF/blob/master/application/accounts/views.py  

Muuten ihan kiitettävän laaja äppi, kunhan viilaa kuntoon.

**Comment by larikkai** [comment]
Kiitos erinomaisesta palautteesta

Käyttöliittymän ja koodin ongelmat korjattu
