### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Pentza** [larikkai/PHoF#3]
Latasin projektin 25.2. klo 20.25

Kokeilin sovellusta paikallisesti. Yritin luoda käyttäjän, mutta sovellus antaa virheilmoituksen, koska User.roles ei sisällä arvoja. Tätä varten voisi dokumentaatioon lisätä asennusohjeet ja mahdolliset ohjeet tietokannan alustukseen. Joudun siis tyytymään Herokuun. 

Herokussa kaikki toiminnallisuudet toimii. Muutamia huomioitavia asioita kuitenkin löytyi. Ensimmäisenä huomasin, että kun luo pelin ja asettaa joukkueille pisteet (vaikkei peli olisi täynnä esim 1/4) näkyy pelin tiedoissa että pelissä olisi täydet pelaajat. Pelissä on todellisuudessa 1/4 pelaajaa mutta siinä näkyy että olisi 4/4 ja siihen pystyy liittymään. 

Kun haluaa lähteä pelistä tai poistaa pelin, pyytää sovellus käyttäjää kirjautumaan. Kitjautuminen kuitenkin hyväksyy minkä tahansa tietokannasta löytyvän käyttäjän tiedot, eikä peli poistu. 

Pelien pistetilanteita ja niiden asettamista ei validoida, siinä lukee että arvo väliltä [0,6], mutta hyväksyy mitä tahansa. 

News sivukin pyytää kirjautumista vaikka on kirjautunut, uudestaan kirjautuminen ei tee mitään, oletan että se pyytää admintunnuksia.

Etusivulla on myös Signup nappi mikä vie sinut rekisteröitymissivulle vaikka olisit kirjautuneena sisään. 

Admin tunnuksia en päässyt kokeilemaan koska sovellus herjaa tunnuksilla admin/test123 "no such username or password"

Itse koodi on mielestäni hyvin jaoiteltu ja nimetty. Tyhjät init.py tiedostot ihmetyttävät. 
HTML on selkeää ja sivut ovat mielestäni oikeassa järjestyksessä oikeine elementteineen.

**Comment by larikkai** [comment]
Kiitos palautteesta, ongelmat korjattu.
